### ISSUE TITLE
About Relationships Documentation

### ISSUE THREAD

**Issue by mklg1982** [abellion/xenus#2]
Hello. I am confuse with Relationships Documentation. I am testing all I can.. but i don't get what I want.
Example: I am using a mongo atlas sandbox cluster which creates **_id** field on the roll. So I create Document Classes with
protected $withId = false; attribute.
Later I have ONE - TO - MANY relationship, we can imagine the examples your documentation teaches us (1 user with several adresses):
Collection Addresses and Document Address (with future fields _id, street, blah... blah..)
Collection Users and Document User (with future fields _id, name, blah.. blah... and **array_of_addresses_ids**)
```
<?php 
use Xenus\Document;

class User extends Document
{
    public function getAddresses()
    {
        return $this->hasMany(Addresses::class, 'user_id');
    }
}

class Address extends Document
{
    public function getUser()
    {
        return $this->belongsTo(Users::class, 'user_id');
    }
}
```

I have 3 questions:

1.  'user_id' in the line of hasMany(Adresses::class, 'user_id') shouldn't be the name of the field where the ids of addresses should be saved, i mean in my case 'array_of_addresses_ids' ???
2. Ok, let's imagine It had worked with the 'user_id'... may i imagine it is an Array of ids or an Array of Address Documents.. or a Cursor of Address Documents??? I ask this, because i want to create my functions **addOneAddress($newAddress)**, because if I use setAddress it will be only one.. no adding but replacing... 
3. Could you forgive me if this is not the right place for questioning for that? Sorry

Thank you so much.

**Comment by abellion** [comment]
Hi,

In a one to many relationship - in the example "one user has many addresses" - you don't need to store the addresses on the user. You can simply have your two documents look like this :

```json
// User
{
  "_id": "..."
}
```

```json
// Address
{
  "_id": "...",
  "user_id": "..."
}
```

When calling the `getAddresses` method of the user's document, the relationship will find in the `Addresses` collection **all** the addresses with a `user_id` equal to your user's unique identifier.

This is the same as if you did the following query :

```php
$addresses->find([
  'user_id' => $user['_id']
]);
```

On the other side, when calling the `getUser` method of the address's document, the relationship will find **one** user whose unique identifier is equal to the address's `user_id` field.

This is the same as if you did the following query :

```php
$users->findOne([
  '_id' => $address['user_id']
]);
```

**Comment by mklg1982** [comment]
Great!!! You are very right!! I should have changed my perspective about the fields in both type of documents.
I can see this clearer now. Thank you so much.
I hope I will be able of seeing the same right perspective when i was finding many to many relationships.
Again, Thank You very much **abellion**.

**Comment by abellion** [comment]
You're welcome !
