### ISSUE TITLE
Is possible to set a whitelist in a Document

### ISSUE THREAD

**Issue by andreinocenti** [abellion/xenus#4]
Hello,

I'm using the Xenus lib in a CakePHP project. I could implement it with no problems. It was very easy to install on it.

Since I started to use I'm trying to find out the best way to "Map" the document. 
I read the full documentation on https://abellion.github.io/xenus/ but I could not find if it is possible.

E.g.: I want the logs document only receive the "datetime" and "message" properties. Is it possible?

Thank you

**Comment by abellion** [comment]
I'm not sure to understand what you mean by "map the document". When creating a document, if you want to make sure it contains only a defined set of properties you can use the `with()` method :

```php
$log = (new Log($content))->with(['datetime', 'message']);
```

In the above example, whatever the given `$content` contains, the resulting document will at most be filled with the `datetime` and `message` properties.

Also, be aware that a `Document` implements the `Iterator` interface, which makes it possible to iterate over it (using a `foreach` or alike).

**Comment by andreinocenti** [comment]
Thank you very much!! I did what I wanted using the with() function. 
Congratulations by the way, you guys developed a great lib!
