### ISSUE TITLE
How Can i inject Connection To All Models? :|

### ISSUE THREAD

**Issue by masihgh** [abellion/xenus#5]
hello thanks for best mongo orm
but ihave a problem:

```php

use Xenus\Collection;
use Xenus\Connection;

trait Model{
    function __construct(){
        return new Connection('mongodb://**', 'Masih');
    }
}

class Users extends Collection
{
    use Model;

    // This is the name of your collection stored in the database
    protected $name = 'users';
}



$users = new Users();
$john = ['name' => 'John'];

// Create
$m = $users->insert($john);
```

> If you use a framework with a dependency injection container, you can configure it to automatically inject an instance of your Xenus\Connection in every collections.

how can i do create this true??

**Comment by abellion** [comment]
Hi,

It depends on which framework you're using, and if you're using one ?

**Comment by masihgh** [comment]
No I using custom MVC
How can I handle models?

**Comment by abellion** [comment]
Then it depends on your specific framework, which I don't know. If you want to stick with your trait, try like that :

```php
trait Model
{
    public function __construct()
    {
        parent::__construct(new Connection('mongodb://**', 'Masih'));
    }
}
```

**Comment by masihgh** [comment]
thanks a lot ;)
